### ISSUE TITLE
Can i ask about the dataset

### ISSUE THREAD

**Issue by Mohamedmtc** [Amgad-Abdelkhaleq/Arabic-Egyptian-Sentiment-Analysis#1]
really great work, i loved your results 
but can I ask about the dataset, are there publications on this dataset? or how the dataset annotated?

**Comment by Amgad-Abdelkhaleq** [comment]
Thanks Mohamed. Sure the dataset is combination of :

Arabic Jordanian General Tweets (AJGT) dataset
paper: https://link.springer.com/chapter/10.1007/978-3-319-60042-0_66
download link: https://github.com/komari6/Arabic-twitter-corpus-AJGT

Dataset of Hotel Reviews scrapped from TripAdvisor.com
paper: https://github.com/hadyelsahar/large-arabic-sentiment-analysis-resouces
download link: https://github.com/hadyelsahar/large-arabic-sentiment-analysis-resouces/blob/master/datasets/HTL.csv
