### ISSUE TITLE
The dataset reference

### ISSUE THREAD

**Issue by FaisalQarah** [Amgad-Abdelkhaleq/Arabic-Egyptian-Sentiment-Analysis#2]
Great work Amgad!!
I would like to know if the dataset used in this project has been published in a research paper. I am interested in using this dataset for my own project and would like to ensure proper credit is given to the original creator.

**Comment by Amgad-Abdelkhaleq** [comment]
Thank you Faisal. The dataset is combination of :

Arabic Jordanian General Tweets (AJGT) dataset
paper: https://link.springer.com/chapter/10.1007/978-3-319-60042-0_66
download link: https://github.com/komari6/Arabic-twitter-corpus-AJGT

Dataset of Hotel Reviews scrapped from TripAdvisor.com
paper: https://github.com/hadyelsahar/large-arabic-sentiment-analysis-resouces
download link: https://github.com/hadyelsahar/large-arabic-sentiment-analysis-resouces/blob/master/datasets/HTL.csv
